dist: trusty
sudo: required

osx_image: xcode9.3

language: c
cache: ccache
git:
    submodules: false
    quiet: true

os:
  - linux
  # - osx

compiler:
  - clang
  - gcc

env:
  - CONFIG_OPTS="" DESTDIR="_install"
  - CONFIG_OPTS="no-asm -Werror --debug no-afalgeng no-shared enable-crypto-mdebug enable-rc5 enable-md2"
  - CONFIG_OPTS="no-asm no-makedepend --strict-warnings -std=c89 -D_DEFAULT_SOURCE" BUILDONLY="yes" CHECKDOCS="yes" GENERATE="yes"

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - g++-6
            - gcc-6
          sources:
            - ubuntu-toolchain-r-test
      compiler: gcc-6
  exclude:
    - os: linux
      compiler: clang
    - os: osx
      compiler: gcc

before_install: 
  - wget -O buck.deb https://github.com/facebook/buck/releases/download/v2018.08.27.01/buck.2018.08.27.01_all.deb
  - sudo dpkg -i buck.deb
  - buck --version
  - wget -O buckaroo.deb https://github.com/LoopPerfect/buckaroo/releases/download/v1.4.1/buckaroo.deb
  - sudo dpkg -i buckaroo.deb
  - buckaroo version

script:
  - buck build :crypto
  - buck build :ssl
